### ISSUE TITLE
Adding a custom faction to WEFERLINGEN version; using GM & VN as base

### ISSUE THREAD

**Issue by TheShade66** [igorkis-scrts/A3-Antistasi-Plus#62]
I am trying to create a custom faction; but since VN is not (yet) supported I would first need to develop the VN support. I will base it on VN 3CB version, and remove all 3CB references.

I am creating a short to do list:

1.  create detector code [DONE]
2.  create selector code [DONE]
3. Create Faction - GM_VN_AI_NATO.sqf [WAIT]
4. Create Faction - GM_VN_AI_PACT.sqf [WAIT]
5. Create Faction -  GM_VN_Civ.sqf [WAIT]
6. Create logistics node \Templates\NewTemplates\GM_VN -> GM_VN_Logistics_Nodes.sqf [DONE] (does this need to be altered?)

I would kindly ask for help in adding VN to supported factions, or at least some guidance on which files need to be modified. I am working full time and will develop this slowly, but am wiling to donate a smaller sum for help & support.

If the project succeeds, I would love to add  it to supported mission settings - no credit needed, if you find it worth the work.

Image is of my current detector code; created 2 new local variables:
![image](https://user-images.githubusercontent.com/89862816/131542357-ddbf6960-3e67-4107-af40-62dcd938cbdd.png)

**Comment by TheShade66** [comment]
![image](https://user-images.githubusercontent.com/89862816/131546980-8a2d47fd-18df-49b8-91ba-ee644942c0c8.png)

![image](https://user-images.githubusercontent.com/89862816/131548126-45491a2b-8965-44c6-98ba-20158591050b.png)

![image](https://user-images.githubusercontent.com/89862816/131548274-df011302-41e8-476f-a841-abcdbfadf420.png)

![image](https://user-images.githubusercontent.com/89862816/131548583-30d47d42-105b-4ae1-82d6-78e224f48baf.png)

![image](https://user-images.githubusercontent.com/89862816/131548727-b62409c9-4942-431c-b497-a6f5f46417fd.png)

Selector done, see images for my code

**Comment by igorkis-scrts** [comment]
Everything seems to be right.
You talked about small issue while editing detector code, what is it?

Also, you don't need a separate `A3A_hasVN_GM` variable - you can operate with `A3A_hasVN` and `A3A_hasGlobMob` and just tie them with the `&&` operator (just like you're already doing it in the selector code).

**Comment by TheShade66** [comment]
Great, thank you igoris!

Can you direct me to where I need to add the VN faction in the files? this is my yesterday's error code, before I added the selector code - this is the error I meant -> it throws an error as if my new variables throw an issue -> will check later today / tommorow with the new selector code

[Uploading Arma3_x64_2021-08-30_20-52-23.zip…]()

**Comment by igorkis-scrts** [comment]
Can't take a look at the zip archive, seems to be it does not successfully uploaded.

**Comment by TheShade66** [comment]
no worries, let me first try it with the latest code updates and report back :)

**Comment by TheShade66** [comment]
[Antistasi%20Plus%20-%20Weferlingen%20GM_VN.gm_weferlingen_summer.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/7086355/Antistasi.20Plus.20-.20Weferlingen.20GM_VN.gm_weferlingen_summer.zip)

Current build - version 1.7.4, need to update to latest 1.7.5 tommorow

**Comment by igorkis-scrts** [comment]
You have some synthax errors which breaks mission load.

Something in detector:
```
21:59:46 Error in expression <Cold war mode is now enabled.",_fileName] call A3A_fnc_log;
};
if (isClass (>
21:59:46   Error position: <] call A3A_fnc_log;
};
21:59:46 File D:\Documents\Arma 3 - Other Profiles\TheNightBird\mpmissions\Antistasi%20Plus%20-%20Weferlingen%20GM_VN.gm_weferlingen_summer\Templates\detector.sqf..., line 64
```

Extra bracket and wrong `VNFactions_GM` position that breaks switch statement:
```
};
    case (A3A_hasVN  && {A3A_hasGlobMob}): {
        ["Templates\NewTemplates\GM_VN\GM_VN_Civ.sqf", civilian] call A3A_fnc_compatibilityLoadFaction;
        [2, "Using GM_VN Civ template", _filename] call A3A_fnc_log;
    };
    "VNFactions_GM" //move this to upper code block
    }; //remove this extra parenthesis
```

**Comment by igorkis-scrts** [comment]
Closing this as this is a discussion topic, not an issue. Feel free to post in Discussions tab.

**Comment by TheShade66** [comment]
thanks for the help, I fixed both issues!

I will reopen as discussion as soon as I have enough free time to migrate to 1.7.5. and start working on the factions part of the code.

Thanks again and will be in touch soon

**Comment by TheShade66** [comment]
@igorkis-scrts hello, I have reopened this issue as a discussion here: https://github.com/igorkis-scrts/A3-Antistasi-Plus/discussions/64

I would kindly ask for your help with the issue!

best regards and thanks in advance

**Comment by igorkis-scrts** [comment]
Usually i don't support not my codebase and don't dive into not my codebase (`when you modify something you lose warranty` policy), but for this time i made an exception.

Fixed both errors:
1. `_loot` error was tied to explicitly disabled SOGPF CDLC in fn_initDisabledMods.sqf file. When SOGPF is enabled, items from only this CDLC will be used in loot crate (to change this, you need to modify fn_equipmentIsValidForCurrentModset).
2. Vehicle Spawn error was tied to that none of trucks you have used have cargo slots. So, it will select any truck from pool instead of throwing error as it was before.

Also, i noticed that you have turned on Spawn Location Selection screen, and i'm not sure if it will work with Antistasi fine, but you may try. Also, you're using outdated AP 1.7.4/ CV 2.5.1 version, latest 1.7.5/2.5.2 version has some pretty important fixes.

[Antistas-Plus-Weferlingen-GM_VN.gm_weferlingen_summer.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/7191643/Antistas-Plus-Weferlingen-GM_VN.gm_weferlingen_summer.zip)

**Comment by TheShade66** [comment]
Thank you!

Yes, migrating to 1.7.5 is on my to-do list, I just wanted to get the current version error free first! I will donate 5 € for your help as soon as I finish the first version of the project :)

I will add cargo slots to the vehicles if needed, thanks for the heads up!

I will try and fix the loot only spawning SOGPF items

The spawn location selection was my first "edit" for my small player group, as we usually allow ourselves to re-spawn on  the track we arrived to mission location with. Playing solo or with two players can be a time sink otherwise, and it seemed to have always worked fine!

I greatly appreciate your help - let me check the current version, and then proceed to updating to 1.7.5. Thank you so much for all your help!

**Comment by TheShade66** [comment]
Sadly, the loot crate is still throwing an error. I do not want to bother you further, so I will wait for the 1.8. update which will add native SOGPF support.

Tehnically the scenario is fully playable as is, except for the loot crate system - thanks for all the help, now it's time for a longer playtime test session :D best!
